apiVersion: v1
kind: Pod
metadata:
  name: mypod9
  namespace: custom-namespace
spec:
 containers:
 - image: k8s.gcr.io/echoserver:1.10
   name: echoserver
   ports:
   - containerPort: 8080
     protocol: TCP
